/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ComponentList: typeof import('./../components/ComponentList.vue')['default']
    Editor: typeof import('./../components/Editor/index.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import("element-plus/es")["ElCard"]
    ElForm: typeof import("element-plus/es")["ElForm"]
    ElFormItem: typeof import("element-plus/es")["ElFormItem"]
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    Grid: typeof import('./../components/Editor/Grid.vue')['default']
    HelloWorld: typeof import('./../components/HelloWorld.vue')['default']
    Home: typeof import("./../view/Home.vue")["default"]
    IconSvg: typeof import('./../components/IconSvg/index.vue')['default']
    IEpInfoFilled: typeof import("~icons/ep/info-filled")["default"]
    IEpSuccessFilled: typeof import("~icons/ep/success-filled")["default"]
    IEpWarningFilled: typeof import("~icons/ep/warning-filled")["default"]
    IEpWarnTriangleFilled: typeof import("~icons/ep/warn-triangle-filled")["default"]
    Main: typeof import("./../components/Main.vue")["default"]
    Mian: typeof import("./../components/mian.vue")["default"]
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Shape: typeof import('./../components/Editor/Shape.vue')['default']
    SvgIcon: typeof import('./../components/SvgIcon/index.vue')['default']
    Toolbar: typeof import('./../components/Toolbar.vue')['default']
  }
}
